#----------------------------------------------------------------------#
#                          entry(class)                                #
#----------------------------------------------------------------------#
# This is a class to store the results of each analysis in an ASH      #
# report sequence, it's position, it's ASH and antigenicty scores, and #
# the sequence that it was compared to. Enties are created by the      #
# seq_to_seq function. Use get_entries getter to retrieve a list of    #
# the entry #objects generated by the creation of an ASH object.       #
#----------------------------------------------------------------------#
class Entry(object):
    # arguments are passed to the contructor by the seq_to_seq function
    def __init__(self, seq, pos, hy_score, str_score,
                                hy_pct, str_pct, analog):
        self.seq       = seq   # the peptide
        self.pos       = pos   # what index is appears
        self.hy_score  = hy_score   # the mismatch score
        self.str_score = str_score  # structural mismatch
        self.analog    = analog     # what it was compared to
        self.hy_pct    = hy_pct
        self.str_pct   = str_pct
